[workspace]
resolver = "2"
members = [
    "minitrace",
    "minitrace-macro",
    "minitrace-jaeger",
    "minitrace-datadog",
    "minitrace-opentelemetry",
    "minitrace-futures",
    "test-statically-disable",
]

[profile.bench]
opt-level = 3
lto = true
